server:
  port: 8051
  servlet:
    context-path: /springboot

mybatis:
  # 对应实体类的包名
  type-aliases-package: com.komiles.study.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/komo?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
