spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/komo?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#   Druid连接池配置
    druid:
#     初始化大小，最小，最大
      initial-size: 5
      max-active: 30
      min-idle: 5
#      获取数据库连接等待的超时时间
      max-wait: 3000
      max-open-prepared-statements: -1
#      配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      time-between-eviction-runs-millis: 60000
#      配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
#      配置连接在池中的最大生存时间
      max-evictable-idle-time-millis: 400000
#      系统启动时通过该sql语句验证数据库是否可用，如果不配置validationQuery，则下面三项无效
      validation-query: SELECT 1
#      启用空闲连接检测，以便回收
      test-while-idle: true
#      从连接池获取连接时，是否检测连接可用性，开启性能会有些许影响
      test-on-borrow: false
#      释放连接到连接池时，是否检测连接可用性，开启性能会有些许影响
      test-on-return: false
#      打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
#      配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      use-global-data-source-stat: true
#      通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

server:
  port: 7080

mybatis:
  # 对应实体类的包名
  type-aliases-package: com.example.druiddemo.dao
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
